directories:
  output: dist_electron
  buildResources: build
appId: com.ollama.chatbot
productName: Ollama Chatbot
files:
  - filter:
      - dist/**/*
      - electron.js
      - ollama-bin/**/*
      - resources/**/*
      - '!dist_electron/**'
extraResources:
  - from: resources/ollama.exe
    to: ollama.exe
    filter:
      - '**/*'
win:
  target: nsis
  icon: public/icon.ico
nsis:
  installerIcon: public/icon.ico
  uninstallerIcon: public/icon.ico
electronVersion: 34.2.0
